[package]
name = "rewatch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.25"
notify = { version = "5.0.0", features = ["serde"] }
serde = "1.0.152"
